### ISSUE TITLE
74AUC1G125 usage bug

### ISSUE THREAD

**Issue by DrAleks40** [mar0x/midi_splitter#1]
В схеме использована 74AUC1G125 при питании +5В. Штатное питание этого чипа ВДВОЕ ниже, максимально допустимое 3.6V! Схема рабочая вообще???

**Comment by DrAleks40** [comment]
Может просто отказаться от 5-6 каналов и пару элементов с 74HC14D пустить вместо 74AUC1G125???

**Comment by mar0x** [comment]
Здравствуйте.
Это опечатка в схеме. Используется SN74LVC1G125. В [midi_splitter-bom.xlsx](https://github.com/mar0x/midi_splitter/blob/master/midi_splitter-bom.xlsx) указан правильный номинал.

Схему поправлю. Спасибо!

**Comment by DrAleks40** [comment]
Ну или просто вместо SN74LVC1G125 поставить еще одну 74HC14D в режиме повторителя с упятеренным выходом? Дешевле кстати.

**Comment by DrAleks40** [comment]
И еще попутно вопрос. Оптрон на AOT127 заменить можно? С изменением цоколевки ессно.

**Comment by mar0x** [comment]
> Оптрон на AOT127 заменить можно?

Почитал [харктеристики](https://www.kondratev-v.ru/uploads_PDF/AOT127-AOT128/AOT127-AOT128.pdf). Судя по ограничению 1.6 В и задержке 10 / 1000 мкс - нельзя.

**Comment by DrAleks40** [comment]
> Судя по ограничению 1.6 В и задержке 10 / 1000 мкс - нельзя.

1.6В - это просто падение на светодиоде, а он током управляется, некритично тут. А вот по задержке - какая здесь нужна? 1 мкс? ИМХО, это избыточно, 1 импульс миди - около 30 мкс, то есть 10 мкс по идее должно хватать.

У 6N138, кстати, максимальное время релакса - 35 мкс! (https://media.digikey.com/pdf/Data%20Sheets/Lite-On%20PDFs/6N138-39%20Series.pdf)

**Comment by mar0x** [comment]
Чем меньше, тем лучше. Важно, чтобы она не сильно отличалась на фронтах иначе будет искажение сигнала. MIDI передаётся на скорости 31250 bit/s т.е. 1 bit - 32 мкс. Разные устройства допускают различные отклонения (где-то 10%).
6N138 добавляет 1-2 мкс на восходящем фронте, на спадающем - меньше. Лучше переходить на 6N137 - он быстрее.

**Comment by DrAleks40** [comment]
Хорошо, спасибо. Вместо SN74LVC1G125 поставить еще одну 74HC14D в режиме повторителя с упятеренным выходом можно?

**Comment by mar0x** [comment]
Можно. Берите тогда сразу инвертированный сигнал с 8й ноги U2 - будет сразу ушестиритель. Царь-сплиттер на 11 выходов!

**Comment by DrAleks40** [comment]
> с 8й ноги U2 - будет сразу ушестиритель.

Упс... А в чем тогда смысл канала на SN74LVC1G125, если JP1 не использовать? На наклейке кстати этот выход (J10) вообще никак не назван. Это что?

**Comment by mar0x** [comment]
Это доработка. Сначала был сплиттер x5, на свободное место добавили выход и буферный элемент. Этикетки "из старых запасов", их много напечатали не выбрасывать же... А джампер на случай, если будет сильное взаимное влияние и придётся поменять источник для U4 на выход из U2 (я не тестировал эту доработку до заказа платы).

**Comment by DrAleks40** [comment]
Ясно. То есть от J10, U4 и т.п. можно вообще безболезненно отказаться. )) А вместо Q1 светодиод запитать от одного из выходов U2. )) Схема сводится к одной микрухе 561ЛН1 и оптрону. )))) Спасибо за разъяснения.

**Comment by mar0x** [comment]
@DrAleks40 Приехали платы для упрощённой схемы "с одной микрухой и оптроном". Если интересно, могу продать комплект для сборки.

**Comment by DrAleks40** [comment]
Интересно. Где глянуть эту вашу схему/плату? Почем комплект для сборки или одна голая плата?



Отправлено из мобильной Почты Mail.Ru


Вторник, 10 мая 2022 г., 12:18 +0300 от ***@***.***  ***@***.***>:
***@***.*** Приехали платы для упрощённой схемы "с одной микрухой и оптроном". Если интересно, могу продать комплект для сборки.

**Comment by mar0x** [comment]
Давайте перейдём в какой-нибудь мессенджер: +7 916 185-06-71

**Comment by DrAleks40** [comment]
Не пользуюсь (кроме авито). В среду в какое время можете на коломенской или ближе к центру-северу? Я заранее позвоню тогда.



Отправлено из мобильной Почты Mail.Ru


Вторник, 10 мая 2022 г., 18:59 +0300 от ***@***.***  ***@***.***>:

**Comment by mar0x** [comment]
В среду буду на Коломенской с 10:30 до 12:00. GitHub, мягко говоря, не для того подобных обсуждений. Ещё есть почта t79161850671@mail.ru.
Хотелось бы понять что Вас интересует (плата, весь набор и т.д.) шильдиков, напр. у меня сейчас нет.
